### PR TITLE
README - Add font-awesome to requirements

### PR DESCRIPTION
**Pull request by brunetton**

### CODE REVIEW

**Comment by vKnmnn** [comment]
Font-Awesome is a optional dependency really, but i don't mind

**Review by vKnmnn — COMMENTED** [review]
this has been resolved in another pull request

**Comment by brunetton** [comment]
> Font-Awesome is a optional dependency really, but i don't mind

🤔 yes in absolute, you're right. But a big part of scripts are using special glyphs; and it can really help users that wonder why theirs blocks are not displayed as in screenshots.
Thanks for merging anyways

**Comment by vKnmnn** [comment]
yes that's why i merged it. i was just being nitpicky ;)

**Pull request closed without merging**
