### PR TITLE
Audio click behavior change

### PR DESCRIPTION
**Pull request by alinalihassan**
Changed behavior from left click right click and middle click to change volume to middle click and scroll

### CODE REVIEW

**Comment by Anachron** [comment]
Hey, thanks for your PR! I would like to merge this,- can you please seperate the bluetooth change from the audio one?

**Comment by alinalihassan** [comment]
Sorry, I didn't knew that it updates the fork with other commits, there you go

**Comment by Anachron** [comment]
@all: Is it really more common to toggle with left-click? I would merge this if people choose for it.

**Comment by vKnmnn** [comment]
due to the lack of participation of some user named @ALL i'll just close this 🤷‍♂

**Pull request closed without merging**
